#!/usr/bin/python
import numpy as np
import pandas as pd
from scipy import stats

# # this file is generated by season_points.py
df = pd.DataFrame.from_csv( 'season_points.csv' )

# a dict of lists, where each list is a randomized estimated set of values for the position
position_values = {}
n_players = {'QB':32,'RB':64,'WR':72,'TE':32,'K':32}

for pos in ['QB', 'RB', 'WR', 'TE', 'K']:
    point_data = df[df.position==pos]['fantasy_points']
    value_dist = stats.gaussian_kde( point_data )
    position_values[pos] = np.sort(value_dist.resample(n_players[pos]))[0][::-1]
    print pos, ': \n', position_values[pos]
